{"level":"info","message":"Test info log.","timestamp":"2024-10-11T00:08:57.642Z"}
{"level":"error","message":"Test error log.","timestamp":"2024-10-11T00:08:57.644Z"}
2024-10-10 20:10:46 [CrewSync360] info: This is an info log message. {"userId":123,"action":"testAction"}
2024-10-10 20:10:46 [CrewSync360] warn: This is a warning log message. {"userId":123}
2024-10-10 20:10:46 [CrewSync360] error: This is an error log message. {"userId":123,"error":{}}
2024-10-10 20:12:07 [CrewSync360] info: This is an info log message.   {"userId":123,"action":"testAction"}
2024-10-10 20:12:07 [CrewSync360] warn: This is a warning log message.   {"userId":123}
2024-10-10 20:12:07 [CrewSync360] error: This is an error log message. Test error Error: Test error
    at testLogging (E:\Code\Crew Sync 360\crewsync360\src\tests\test-logger.js:47:71)
    at Object.<anonymous> (E:\Code\Crew Sync 360\crewsync360\src\tests\test-logger.js:51:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {"userId":123}
